apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "@{{module_name}}.fullname" . }}
{{- if .Values.image.pullSecret }}
imagePullSecrets: 
  - name: {{ .Values.image.pullSecret }}
{{- end }}
