apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "@{{module_name}}.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "@{{module_name}}name" . }}
    helm.sh/chart: {{ include "@{{module_name}}.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "@{{module_name}}.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}    
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "@{{module_name}}.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - readOnly: true
              mountPath: /etc/conf
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ include "@{{module_name}}.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
